// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQPYLPnvxIr5n48brBfc_jNwt1o5sLc0',
    appId: '1:1029846276923:web:bddc77299573d18de2b51e',
    messagingSenderId: '1029846276923',
    projectId: 'form-47277',
    authDomain: 'form-47277.firebaseapp.com',
    storageBucket: 'form-47277.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDULwiTgfgWl31hHTgtYkEeqTxLqNie138',
    appId: '1:1029846276923:android:87220ce114708e8ce2b51e',
    messagingSenderId: '1029846276923',
    projectId: 'form-47277',
    storageBucket: 'form-47277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyjYWb0CuR7WzFO7k2v7-j-h8johXyz-E',
    appId: '1:1029846276923:ios:56128ff682faa459e2b51e',
    messagingSenderId: '1029846276923',
    projectId: 'form-47277',
    storageBucket: 'form-47277.appspot.com',
    iosBundleId: 'com.example.interview',
  );
}
